#! /usr/bin/python3

# Set (/usr/bin/python /usr/local/bin/system-update.py) to run in /etc/crontab file for suspending
# Set (/usr/bin/python /usr/local/bin/system-update.py) to run in /etc/rc.local (Before Login) to start back up

import subprocess
import os
import datetime
import time

todaydate = str(datetime.date.today())
todaytime = str(datetime.datetime.today())


#START VMWARE GUESTS BACK UP
time.sleep(10)
if os.path.exists('/var/log/vmware_logs/reboot.log'):
	flog = open('/var/log/vmware_logs/' + todaydate + '-' + 'vmware_update.log', 'a')
	for i in open('/var/log/vmware_logs/reboot.log').read().splitlines():
		subprocess.call('/usr/bin/vmrun start ' + i.replace('(','\(').replace(')','\)').replace(' ','\ ') + ' nogui', shell=True)
		flog.write(todaytime + ':' + i + ' This system has been started' + '\n')
	flog.close()
	os.system('rm -rf /var/log/vmware_logs/reboot.log')


#SUSPEND VMWARE GUESTS
elif not os.path.exists('/var/log/vmware_logs/reboot.log'):
	vmguests = (subprocess.check_output('/usr/bin/vmrun list | grep "vmware"', shell=True).splitlines())

	for i in vmguests:
		print i
		flog = open('/var/log/vmware_logs/' + todaydate + '-' + 'vmware_update.log', 'a')
		fsys = open('/var/log/vmware_logs/reboot.log', 'a')
		subprocess.call('/usr/bin/vmrun suspend ' + i.replace('(','\(').replace(')','\)').replace(' ','\ '), shell=True)
		flog.write(todaytime + ':' + i + ' This system has been suspended' + '\n')
		fsys.write(i + '\n')
		#time.sleep(5)
	flog.close()
	fsys.close()

#REBOOT DESKTOP
	if len(subprocess.check_output('vmrun list', shell=True).splitlines()) == 1:
                flog = open('/var/log/vmware_logs/' + todaydate + '-' + 'vmware_update.log', 'a')
                flog.write(todaytime + ' Desktop has been rebooted' + '\n')
                flog.close()
                os.system('/sbin/shutdown -r now')

else:
	print 'Good Bye!'
